
# Global config for all parts of the analysis
version = "1.0"
out_dir = "./out"
temp_dir = "./temp"

[logging]
log_dir = "./logs"
level = "DEBUG"

[datasets]
destinations    = "data/processed/Destinations.gpkg"
lsoa_boundaries = "data/processed/LSOA_Boundaries.gpkg"
msoa_boundaries = "data/processed/MSOA_Boundaries.gpkg"
centriods       = "data/processed/LSOA_Centres.gpkg"
regions         = "data/processed/Regions.gpkg"
ruc_definitions = "data/processed/ruc_definitions"
england_osm     = "data/raw/england-260119.osm.pbf"

[datasets.gtfs]
east_anglia   = "data/processed/gtfs/east_anglia_clean.zip"
london        = "data/processed/gtfs/london_clean.zip"
north_east    = "data/processed/gtfs/north_east_clean.zip"
north_west    = "data/processed/gtfs/north_west_clean.zip"
south_east    = "data/processed/gtfs/south_east_clean.zip"
south_west    = "data/processed/gtfs/south_west_clean.zip"
east_midlands = "data/processed/gtfs/east_midlands_clean.zip"
west_midlands = "data/processed/gtfs/west_midlands_clean.zip"
yorkshire     = "data/processed/gtfs/yorkshire_clean.zip"

[isochrones]
save_index = 5
bbox_radius = 70000
gtfs_distance = 20000
departure = 2026-01-26 08:30:00
departure_window = 60
travel_time = 40
bus_grid_res = 250
bus_percentile = 25
car_grid_res = 500
car_percentile = 50